name: Rename PDF Files

on:
  workflow_dispatch:

jobs:
  rename:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Rename PDFs
        run: |
          python <<EOF
          import os
          import re

          for file in os.listdir():
              if file.endswith(".pdf"):

                  lower = file.lower()

                  if "arabic" in lower or "عربي" in lower:
                      subject = "arabic"

                  elif "english" in lower:
                      subject = "english"

                  elif "حياء" in lower:
                      subject = "biology"

                  elif "physics" in lower or "فيزياء" in lower:
                      subject = "physics"

                  elif "chemistry" in lower or "كيمياء" in lower:
                      subject = "chemistry"

                  elif "basic" in lower or "أساسية" in lower:
                      subject = "math-basic"

                  elif "advance" in lower or "متقدمة" in lower:
                      subject = "math-advance"

                  else:
                      subject = "other"

                  year = re.findall(r'20\\d{2}', lower)

                  if year:
                      year = year[0]
                  else:
                      year = "unknown"

                  new_name = f"{subject}-{year}.pdf"

                  if file != new_name:
                      print(file, "->", new_name)
                      os.rename(file, new_name)

          EOF

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add .
          git commit -m "Rename files automatically" || echo "No changes"

          git push
